import PropTypes from "prop-types";

export const propTypes = {
    label: PropTypes.string,
    labelRow: PropTypes.bool,
    help: PropTypes.string,
    multiple: PropTypes.bool,
    onValueChange: PropTypes.func,
    
    containerProps: PropTypes.object,
    labelContainerProps: PropTypes.object,
    labelProps: PropTypes.object,
    requiredStarProps: PropTypes.object,
    helpProps: PropTypes.object,
    inputProps: PropTypes.object,
    listAndButtonsContainerProps: PropTypes.object,
    listProps: PropTypes.object,
    listItemProps: PropTypes.object,
    urlInputProps: PropTypes.object,
    originInputProps: PropTypes.object,
    iconProps: PropTypes.object,
    titleProps: PropTypes.object,
    deleteButtonProps: PropTypes.object,
    deleteButtonIconProps: PropTypes.object,
    panelProps: PropTypes.object,
    videoProps: PropTypes.object,
    titleInputProps: PropTypes.object,
    descriptionInputProps: PropTypes.object,
    buttonContainerProps: PropTypes.object,
    cameraButtonProps: PropTypes.object,
    cameraButtonSpinnerProps: PropTypes.object,
    cameraButtonIconProps: PropTypes.object,
    cameraButtonLabelProps: PropTypes.object,
    filesButtonProps: PropTypes.object,
    filesButtonSpinnerProps: PropTypes.object,
    filesButtonIconProps: PropTypes.object,
    filesButtonLabelProps: PropTypes.object,
};
