
const notes = [
    {
        rowid: 0,
        localId: 0,
        type: "prospection-client",
        status: 1, // 0 => brouillon, 1 => sauvegardée
        label: "Clinique St-Clair",
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consectetur, quibusdam soluta voluptate repellendus, repellat ex fuga distinctio veniam voluptatum vero tempora placeat ipsum impedit doloribus! Voluptates distinctio adipisci magnam quod?",
        point: [],
        potentiel_affaires: 1000,
        activity_domain: "Santé",
        updated_at: 1737115200,
        created_at: 1736683200,
    },
    {
        localId: 1,
        type: "prospection-client",
        status: 0, // 0 => brouillon, 1 => sauvegardée
        label: "Hôtel Lebeaulieu",
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consectetur, quibusdam soluta voluptate repellendus, repellat ex fuga distinctio veniam voluptatum vero tempora placeat ipsum impedit doloribus! Voluptates distinctio adipisci magnam quod?",
        point: [],
        potentiel_affaires: 1000,
        activity_domain: "Hôtellerie",
        updated_at: 1737111600,
        created_at: 1736766000,
    },
    {
        rowid: 1,
        localId: 2,
        type: "prospection-client",
        status: 1, // 0 => brouillon, 1 => sauvegardée
        label: "Superrette 13 Marseille",
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consectetur, quibusdam soluta voluptate repellendus, repellat ex fuga distinctio veniam voluptatum vero tempora placeat ipsum impedit doloribus! Voluptates distinctio adipisci magnam quod?",
        point: [],
        potentiel_affaires: 1000,
        activity_domain: "Petite distribution",
        updated_at: 1737025200,
        created_at: 1737010800,
    },
    {
        rowid: 2,
        localId: 3,
        type: "prospection-client",
        status: 1, // 0 => brouillon, 1 => sauvegardée
        label: "Restaurant Ecume",
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consectetur, quibusdam soluta voluptate repellendus, repellat ex fuga distinctio veniam voluptatum vero tempora placeat ipsum impedit doloribus! Voluptates distinctio adipisci magnam quod?",
        point: [],
        potentiel_affaires: 1000,
        activity_domain: "Restauration",
        updated_at: 1737014400,
        created_at: 1737003600,
    },
    {
        rowid: 3,
        localId: 4,
        type: "prospection-client",
        status: 1, // 0 => brouillon, 1 => sauvegardée
        label: "NASA",
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consectetur, quibusdam soluta voluptate repellendus, repellat ex fuga distinctio veniam voluptatum vero tempora placeat ipsum impedit doloribus! Voluptates distinctio adipisci magnam quod?",
        point: [],
        potentiel_affaires: 2000000000,
        activity_domain: "Recherche",
        updated_at: 1736830800,
        created_at: 1736506800,
    },
    {
        rowid: 4,
        localId: 5,
        type: "visite-d-entretien",
        status: 1, // 0 => brouillon, 1 => sauvegardée
        label: "Bureaux E.M Six-fours",
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consectetur, quibusdam soluta voluptate repellendus, repellat ex fuga distinctio veniam voluptatum vero tempora placeat ipsum impedit doloribus! Voluptates distinctio adipisci magnam quod?",
        point: [],
        etatvetust: "Bon état",
        assurance: "Grande distribution",
        syndic: false,
        updated_at: 1736499600,
        created_at: 1736492400,
    },
    {
        rowid: 5,
        localId: 6,
        type: "test-produit",
        status: 1, // 0 => brouillon, 1 => sauvegardée
        label: "Bugatti Veron",
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consectetur, quibusdam soluta voluptate repellendus, repellat ex fuga distinctio veniam voluptatum vero tempora placeat ipsum impedit doloribus! Voluptates distinctio adipisci magnam quod?",
        point: [],
        updated_at: 1736503200,
        created_at: 1736499600,
    },
    {
        rowid: 6,
        localId: 7,
        type: "test-produit",
        status: 2, // 0 => brouillon, 1 => sauvegardée
        label: "Yatch 38X Bella",
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consectetur, quibusdam soluta voluptate repellendus, repellat ex fuga distinctio veniam voluptatum vero tempora placeat ipsum impedit doloribus! Voluptates distinctio adipisci magnam quod?",
        point: [],
        updated_at: 1736546400,
        created_at: 1736499600,
    },
    {
        rowid: 4,
        user: 1,
        localId: 5,
        type: "visite-d-entretien",
        status: 1, // 0 => brouillon, 1 => sauvegardée
        label: "Bureaux E.M Six-fours",
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consectetur, quibusdam soluta voluptate repellendus, repellat ex fuga distinctio veniam voluptatum vero tempora placeat ipsum impedit doloribus! Voluptates distinctio adipisci magnam quod?",
        point: [],
        etatvetust: "Bon état",
        assurance: "Grande distribution",
        syndic: false,
        updated_at: 1736499600,
        created_at: 1736492400,
    },
    {
        rowid: 5,
        user: 1,
        localId: 6,
        type: "test-produit",
        status: 1, // 0 => brouillon, 1 => sauvegardée
        label: "Bugatti Veron",
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consectetur, quibusdam soluta voluptate repellendus, repellat ex fuga distinctio veniam voluptatum vero tempora placeat ipsum impedit doloribus! Voluptates distinctio adipisci magnam quod?",
        point: [],
        updated_at: 1736503200,
        created_at: 1736499600,
    },
    {
        rowid: 6,
        user: 2,
        localId: 7,
        type: "test-produit",
        status: 2, // 0 => brouillon, 1 => sauvegardée
        label: "Yatch 38X Bella",
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consectetur, quibusdam soluta voluptate repellendus, repellat ex fuga distinctio veniam voluptatum vero tempora placeat ipsum impedit doloribus! Voluptates distinctio adipisci magnam quod?",
        point: [],
        updated_at: 1736546400,
        created_at: 1736499600,
    },
];

export default notes;