import PropTypes from "prop-types";

export const propTypes = {
    label: PropTypes.string,
    labelRow: PropTypes.bool,
    help: PropTypes.string,
    multiple: PropTypes.bool,
    onValueChange: PropTypes.func,
    
    containerProps: PropTypes.object,
    labelContainerProps: PropTypes.object,
    labelProps: PropTypes.object,
    requiredStarProps: PropTypes.object,
    helpProps: PropTypes.object,
    inputProps: PropTypes.object,
    listAndButtonsContainerProps: PropTypes.object,
    listProps: PropTypes.object,
    listItemProps: PropTypes.object,
    urlInputProps: PropTypes.object,
    typeInputProps: PropTypes.object,
    iconProps: PropTypes.object,
    titleProps: PropTypes.object,
    typeProps: PropTypes.object,
    deleteButtonProps: PropTypes.object,
    deleteButtonIconProps: PropTypes.object,
    panelProps: PropTypes.object,
    fileProps: PropTypes.object,
    titleInputProps: PropTypes.object,
    descriptionInputProps: PropTypes.object,
    buttonProps: PropTypes.object,
    buttonSpinnerProps: PropTypes.object,
    buttonIconProps: PropTypes.object,
    buttonLabelProps: PropTypes.object,
};
