import PropTypes from "prop-types";

export const propTypes = {
  label: PropTypes.string,
  help: PropTypes.string,
  icon: PropTypes.node,
  hasCopyButton: PropTypes.bool, 
  type: PropTypes.string,
  placeholder: PropTypes.string,
  required: PropTypes.bool,
  disabled: PropTypes.bool,
  readOnly: PropTypes.bool,
  min: PropTypes.number,
  max: PropTypes.number,
  minLength: PropTypes.number,
  maxLength: PropTypes.number,
  name: PropTypes.string,
  pattern: PropTypes.string,
  step: PropTypes.number,
  value: PropTypes.any,
  onChange: PropTypes.func,
  defaultValue: PropTypes.any,

  containerProps: PropTypes.object,
  labelContainerProps: PropTypes.object,
  labelProps: PropTypes.object,
  starProps: PropTypes.object,
  childrenContainerProps: PropTypes.object,
  helpProps: PropTypes.object,
  prefixProps: PropTypes.object,
  suffixProps: PropTypes.object, 
  inputContainerProps: PropTypes.object,
  Spinner: PropTypes.object,
  iconProps: PropTypes.object,
  inputProps: PropTypes.object,
  MinusButton: PropTypes.object,
  PlusButton: PropTypes.object,
  PasswordButton: PropTypes.object,
  CopyButton: PropTypes.object,
};