const a = () => {
    return (
        <a
            // about="" // RDFa
            accessKey=""
            autoCapitalize=""
            autoCorrect=""
            autoFocus
            autoSave=""
            children
            className=""
            color=""
            content=""
            contentEditable
            contextMenu=""
            dangerouslySetInnerHTML={}
            datatype=""
            defaultChecked
            defaultValue={}
            dir=""
            download={}
            draggable
            enterKeyHint=""
            hidden
            href=""
            hrefLang=""
            i18nIsDynamicList
            id=""
            inlist={}
            inputMode=""
            is=""
            itemID=""
            itemProp=""
            itemRef=""
            itemScope
            itemType=""
            key={}
            lang=""
            media=""
            nonce=""
            ping=""
            prefix=""
            property=""
            radioGroup=""
            ref={}
            referrerPolicy=""
            rel=""
            resource=""
            results={}
            rev=""
            role=""
            security=""
            slot=""
            spellCheck
            style={}
            suppressContentEditableWarning
            suppressHydrationWarning
            tabIndex={}
            target=""
            title=""
            translate=""
            type=""
            typeof=""
            unselectable=""
            vocab=""
        >

        </a>
    );
}