const img = () => {
    return (
        <img
            // about="" // RDFa
            accessKey=""
            alt=""
            autoCapitalize=""
            autoCorrect=""
            autoFocus
            autoSave=""
            children
            className=""
            color=""
            content=""
            contentEditable
            contextMenu=""
            crossOrigin=""
            dangerouslySetInnerHTML={}
            datatype=""
            decoding=""
            defaultChecked
            defaultValue={}
            dir=""
            draggable
            enterKeyHint=""
            height={}
            hidden
            i18nIsDynamicList
            id=""
            inlist={}
            inputMode=""
            is=""
            itemID=""
            itemProp=""
            itemRef=""
            itemScope
            itemType=""
            key={}
            lang=""
            loading=""
            nonce=""
            prefix=""
            property=""
            radioGroup=""
            ref={}
            referrerPolicy=""
            rel=""
            resource=""
            results={}
            rev=""
            role=""
            security=""
            sizes=""
            slot=""
            spellCheck
            src=""
            srcSet=""
            style={}
            suppressContentEditableWarning
            suppressHydrationWarning
            tabIndex={}
            title=""
            translate=""
            typeof=""
            unselectable=""
            useMap=""
            vocab=""
            width={}
        />
    );
}