const time = () => {
    return (
        <time
            // about="" // RDFa
            accessKey=""
            autoCapitalize=""
            autoCorrect=""
            autoFocus
            autoSave=""
            children
            className=""
            color=""
            content=""
            contentEditable
            contextMenu=""
            dangerouslySetInnerHTML={}
            datatype=""
            dateTime=""
            defaultChecked
            defaultValue={}
            dir=""
            draggable
            enterKeyHint=""
            hidden
            i18nIsDynamicList
            id=""
            inlist={}
            inputMode=""
            is=""
            itemID=""
            itemProp=""
            itemRef=""
            itemScope
            itemType=""
            key={}
            lang=""
            nonce=""
            prefix=""
            property=""
            radioGroup=""
            ref={}
            rel=""
            resource=""
            results={}
            rev=""
            role=""
            security=""
            slot=""
            spellCheck
            style={}
            suppressContentEditableWarning
            suppressHydrationWarning
            tabIndex={}
            title=""
            translate=""
            typeof=""
            unselectable=""
            vocab=""
>

        </time>
    );
}