const video = () => {
    return (
        <video
            // about="" // RDFa
            accessKey=""
            autoCapitalize=""
            autoCorrect=""
            autoFocus
            autoPlay
            autoSave=""
            children
            className=""
            color=""
            content=""
            contentEditable
            contextMenu=""
            controls
            controlsList=""
            crossOrigin=""
            dangerouslySetInnerHTML={}
            datatype=""
            defaultChecked
            defaultValue={}
            dir=""
            disablePictureInPicture
            disableRemotePlayback
            draggable
            enterKeyHint=""
            height={}
            hidden
            i18nIsDynamicList
            id=""
            inlist={}
            inputMode=""
            is=""
            itemID=""
            itemProp=""
            itemRef=""
            itemScope
            itemType=""
            key={}
            lang=""
            loop
            mediaGroup=""
            muted
            playsInline
            poster=""
            prefix=""
            preload=""
            property=""
            radioGroup=""
            ref={}
            rel=""
            resource=""
            results={}
            rev=""
            role=""
            security=""
            slot=""
            spellCheck
            src=""
            style={}
            suppressContentEditableWarning
            suppressHydrationWarning
            tabIndex={}
            title=""
            translate=""
            typeof=""
            unselectable=""
            width={}
        >

        </video>
    );   
}